### ISSUE TITLE
Option to skip green-time- and blank / unmeasured lines in the output

### ISSUE THREAD

**Issue by ajans** [digitalarbeiter/zeitdieb#1]
Hi,

I am just testing the contextmanager-mode of zeitdieb and I think it's very useful and easy to use, thank you!

As a suggestion, I would like to have an option for the measurement-output to skip green-time-measured code-lines and skipped lines (blank lines or code-lines that were skipped due to if-guards).

Or is there such an option already?

**Comment by L3viathan** [comment]
There's no such option, but it sounds like a good idea. 

I wonder if we would want a separate threshold there, or if "hide anything green or better" is sufficient.

**Comment by L3viathan** [comment]
I added a `q` flag. Release comes later, can't do that from my phone.

**Comment by ajans** [comment]
> I wonder if we would want a separate threshold there, or if "hide anything green or better" is sufficient.

For me, at least, it is sufficient to skip "green or better" lines and un-executed lines.

Thank you very much, I will test this feature as soon as you can release!

**Comment by L3viathan** [comment]
Released 0.3.0 with this feature, also added gap markers; see screenshot (unless you use the "very quiet" `Q` flag instead).

<img width="343" alt="image" src="https://github.com/user-attachments/assets/0c23e855-3586-41ed-b24e-0633151434a6">
